In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('final_ds.csv')

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
sample_df = df.sample(5)
sample_df

,Patient Number,Age,Sex,Ethnicity,Marital Status,Clarity,Color,Transparency,Spec Gravity,pH Level,Leukocytes,Nitrite,Protein,Glucose,Ketones,Urobilinogen,Bilirubin,Blood,Bacteria,Epithelial Cells,RBC,WBC,Mucus Threads,Amorphous Urate/Phosphate,DIAGNOSIS
238,239,36.0,FEMALE,FILIPINO,MARRIED,DECREASED,PALE YELLOW,HAZY,1.005,6.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NORMAL,NEGATIVE,NEGATIVE,RARE,FEW,0-2,0-2,MODERATE,RARE,NEGATIVE
90,91,28.0,FEMALE,FILIPINO,SINGLE,DECREASED,YELLOW,CLOUDY,1.005,7.0,2+,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NORMAL,NEGATIVE,2+,MANY,MANY,20-30,20-30,MANY,MANY,UTI
349,350,52.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.005,6.0,NEGATIVE,NEGATIVE,NEGATIVE,TRACE,NEGATIVE,NORMAL,NEGATIVE,NEGATIVE,FEW,MODERATE,0-2,0-2,MODERATE,MODERATE,NEGATIVE
235,236,28.0,FEMALE,FILIPINO,SINGLE,DECREASED,DARK YELLOW,HAZY,1.025,6.0,2+,NEGATIVE,TRACE,NEGATIVE,NEGATIVE,NORMAL,NEGATIVE,TRACE,FEW,MODERATE,5-10,20-30,FEW,FEW,UTI
55,56,32.0,FEMALE,FILIPINO,MARRIED,DECREASED,LIGHT YELLOW,HAZY,1.005,6.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NORMAL,NEGATIVE,NEGATIVE,FEW,FEW,0-2,0-2,MODERATE,RARE,NEGATIVE

In [5]:
df = df.iloc[:, 1:]

In [6]:
df['Urobilinogen'] = df['Urobilinogen'].replace('NORMAL', 1)
df['Urobilinogen'] = df['Urobilinogen'].replace('NORMAL', 1).apply(lambda x: int(float(str(x).split()[0])) if isinstance(x, str) and any(char.isdigit() for char in x) else x)

In [7]:
df = df[df['Ethnicity'] == 'FILIPINO'].copy()

In [8]:
for column in df.columns:
    print(f"Unique values in {column}:")
    print(df[column].unique())  
    print()

Unique values in Age:
[2.300e+01 4.400e+01 2.200e+01 1.600e+01 1.800e+01 3.800e+01 3.200e+01
 3.700e+01 1.100e+01 5.200e+01 5.100e+01 3.500e+01 2.500e+01 1.700e+01
 5.300e+01 5.900e+01 1.200e+01 6.000e+01 3.600e+01 4.100e+01 2.800e+01
 2.600e+01 2.000e+01 1.300e+01 4.000e+01 3.000e+01 4.000e+00 4.500e+01
 1.500e+01 6.667e-01 3.000e+00 6.000e+00 1.000e+01 1.000e+00 5.000e+01
 8.000e+00 3.300e+01 4.600e+01 5.700e+01 3.400e+01 2.700e+01 7.300e+01
 6.600e+01 3.100e+01 2.900e+01 4.300e+01 7.700e+01 4.700e+01 2.400e+01
 5.800e+01 1.400e+01 1.900e+01 5.600e+01 2.100e+01 4.900e+01 4.200e+01
 5.000e+00 5.500e+01 3.900e+01 5.400e+01 2.000e+00 7.000e+00 8.330e-02
 6.300e+01 9.000e+00 4.800e+01 8.800e+01 5.000e-01 6.200e+01 7.200e+01
 8.200e+01 6.400e+01 6.500e+01]

Unique values in Sex:
['FEMALE' 'MALE']

Unique values in Ethnicity:
['FILIPINO']

Unique values in Marital Status:
['SINGLE' 'MARRIED' 'WIDOW']

Unique values in Clarity:
['INCREASED' 'DECREASED']

Unique values in Color:
['YELLOW' 'DARK YELLOW' 'LIGHT YELLOW' 'AMBER' 'CLEAR' 'PALE YELLOW' 'RED'
 'BROWN' 'STRAW']

Unique values in Transparency:
['CLEAR' 'CLOUDY' 'HAZY' 'TURBID' 'MILKY']

Unique values in Spec Gravity:
[1.005 1.02  1.025 1.01  1.015 1.03 ]

Unique values in pH Level:
[5.  6.  6.5 7.  7.5 8. ]

Unique values in Leukocytes:
['NEGATIVE' '3+' 'TRACE' '2+' '1+']

Unique values in Nitrite:
['NEGATIVE' 'TRACE' 'POSITIVE']

Unique values in Protein:
['NEGATIVE' '1+' 'TRACE' '2+' '3+' '4+']

Unique values in Glucose:
['NEGATIVE' '2+' 'TRACE' '1+' '3+' '4+']

Unique values in Ketones:
['NEGATIVE' 'TRACE' '3+' '1+' '4+' '2+']

Unique values in Urobilinogen:
[1 4]

Unique values in Bilirubin:
['NEGATIVE' 'TRACE' '2+' '3+' '1+']

Unique values in Blood:
['NEGATIVE' '2+' '3+' '1+' 'TRACE']

Unique values in Bacteria:
['FEW' 'MODERATE' 'MANY' 'RARE' 'TNTC']

Unique values in Epithelial Cells:
['FEW' 'MANY' 'MODERATE' 'TNTC' 'RARE']

Unique values in RBC:
['0-2' '20-30' 'TNTC' ' 10-20' ' 5-10']

Unique values in WBC:
['0-2' 'TNTC' ' 5-10' '20-30' ' 10-20']

Unique values in Mucus Threads:
['FEW' 'MANY' 'MODERATE' 'RARE']

Unique values in Amorphous Urate/Phosphate:
['RARE' 'FEW' 'MODERATE' 'MANY']

Unique values in DIAGNOSIS:
['NEGATIVE' 'UTI']

In [9]:
null_rows = df[df.isnull().any(axis=1)]
print("Rows with null values:")
print(null_rows)

Rows with null values:
Empty DataFrame
Columns: [Age, Sex, Ethnicity, Marital Status, Clarity, Color, Transparency, Spec Gravity, pH Level, Leukocytes, Nitrite, Protein, Glucose, Ketones, Urobilinogen, Bilirubin, Blood, Bacteria, Epithelial Cells, RBC, WBC, Mucus Threads, Amorphous Urate/Phosphate, DIAGNOSIS]
Index: []

In [10]:
for column in df.columns:
    print(f"Unique values in {column}:")
    print(df[column].unique())  
    print()

Unique values in Age:
[2.300e+01 4.400e+01 2.200e+01 1.600e+01 1.800e+01 3.800e+01 3.200e+01
 3.700e+01 1.100e+01 5.200e+01 5.100e+01 3.500e+01 2.500e+01 1.700e+01
 5.300e+01 5.900e+01 1.200e+01 6.000e+01 3.600e+01 4.100e+01 2.800e+01
 2.600e+01 2.000e+01 1.300e+01 4.000e+01 3.000e+01 4.000e+00 4.500e+01
 1.500e+01 6.667e-01 3.000e+00 6.000e+00 1.000e+01 1.000e+00 5.000e+01
 8.000e+00 3.300e+01 4.600e+01 5.700e+01 3.400e+01 2.700e+01 7.300e+01
 6.600e+01 3.100e+01 2.900e+01 4.300e+01 7.700e+01 4.700e+01 2.400e+01
 5.800e+01 1.400e+01 1.900e+01 5.600e+01 2.100e+01 4.900e+01 4.200e+01
 5.000e+00 5.500e+01 3.900e+01 5.400e+01 2.000e+00 7.000e+00 8.330e-02
 6.300e+01 9.000e+00 4.800e+01 8.800e+01 5.000e-01 6.200e+01 7.200e+01
 8.200e+01 6.400e+01 6.500e+01]

Unique values in Sex:
['FEMALE' 'MALE']

Unique values in Ethnicity:
['FILIPINO']

Unique values in Marital Status:
['SINGLE' 'MARRIED' 'WIDOW']

Unique values in Clarity:
['INCREASED' 'DECREASED']

Unique values in Color:
['YELLOW' 'DARK YELLOW' 'LIGHT YELLOW' 'AMBER' 'CLEAR' 'PALE YELLOW' 'RED'
 'BROWN' 'STRAW']

Unique values in Transparency:
['CLEAR' 'CLOUDY' 'HAZY' 'TURBID' 'MILKY']

Unique values in Spec Gravity:
[1.005 1.02  1.025 1.01  1.015 1.03 ]

Unique values in pH Level:
[5.  6.  6.5 7.  7.5 8. ]

Unique values in Leukocytes:
['NEGATIVE' '3+' 'TRACE' '2+' '1+']

Unique values in Nitrite:
['NEGATIVE' 'TRACE' 'POSITIVE']

Unique values in Protein:
['NEGATIVE' '1+' 'TRACE' '2+' '3+' '4+']

Unique values in Glucose:
['NEGATIVE' '2+' 'TRACE' '1+' '3+' '4+']

Unique values in Ketones:
['NEGATIVE' 'TRACE' '3+' '1+' '4+' '2+']

Unique values in Urobilinogen:
[1 4]

Unique values in Bilirubin:
['NEGATIVE' 'TRACE' '2+' '3+' '1+']

Unique values in Blood:
['NEGATIVE' '2+' '3+' '1+' 'TRACE']

Unique values in Bacteria:
['FEW' 'MODERATE' 'MANY' 'RARE' 'TNTC']

Unique values in Epithelial Cells:
['FEW' 'MANY' 'MODERATE' 'TNTC' 'RARE']

Unique values in RBC:
['0-2' '20-30' 'TNTC' ' 10-20' ' 5-10']

Unique values in WBC:
['0-2' 'TNTC' ' 5-10' '20-30' ' 10-20']

Unique values in Mucus Threads:
['FEW' 'MANY' 'MODERATE' 'RARE']

Unique values in Amorphous Urate/Phosphate:
['RARE' 'FEW' 'MODERATE' 'MANY']

Unique values in DIAGNOSIS:
['NEGATIVE' 'UTI']

In [11]:
df.sample(20)

,Age,Sex,Ethnicity,Marital Status,Clarity,Color,Transparency,Spec Gravity,pH Level,Leukocytes,Nitrite,Protein,Glucose,Ketones,Urobilinogen,Bilirubin,Blood,Bacteria,Epithelial Cells,RBC,WBC,Mucus Threads,Amorphous Urate/Phosphate,DIAGNOSIS
262,37.0,MALE,FILIPINO,SINGLE,DECREASED,DARK YELLOW,HAZY,1.025,6.0,TRACE,NEGATIVE,TRACE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,MODERATE,MODERATE,0-2,5-10,FEW,FEW,UTI
147,25.0,MALE,FILIPINO,SINGLE,DECREASED,RED,TURBID,1.020,6.5,3+,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,2+,RARE,FEW,20-30,TNTC,MODERATE,FEW,UTI
324,32.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.020,5.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,RARE,FEW,0-2,0-2,FEW,RARE,NEGATIVE
267,60.0,MALE,FILIPINO,MARRIED,DECREASED,DARK YELLOW,CLOUDY,1.030,6.0,3+,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,MODERATE,MODERATE,0-2,TNTC,MODERATE,MANY,UTI
137,30.0,FEMALE,FILIPINO,SINGLE,DECREASED,YELLOW,HAZY,1.020,5.0,TRACE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,FEW,FEW,0-2,5-10,FEW,FEW,UTI
355,16.0,FEMALE,FILIPINO,SINGLE,DECREASED,PALE YELLOW,HAZY,1.005,5.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,RARE,FEW,0-2,0-2,FEW,RARE,NEGATIVE
408,46.0,FEMALE,FILIPINO,MARRIED,DECREASED,LIGHT YELLOW,HAZY,1.015,6.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,RARE,FEW,0-2,0-2,FEW,RARE,NEGATIVE
92,47.0,MALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.015,6.5,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,FEW,FEW,0-2,0-2,FEW,FEW,NEGATIVE
233,10.0,MALE,FILIPINO,SINGLE,DECREASED,YELLOW,HAZY,1.015,6.5,TRACE,NEGATIVE,1+,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,MODERATE,MODERATE,0-2,10-20,MODERATE,FEW,UTI
220,38.0,FEMALE,FILIPINO,MARRIED,DECREASED,PALE YELLOW,HAZY,1.005,6.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,1+,FEW,FEW,10-20,0-2,FEW,FEW,UTI
193,33.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.010,6.0,NEGATIVE,NEGATIVE,NEGATIVE,4+,NEGATIVE,1,NEGATIVE,TRACE,MODERATE,MODERATE,5-10,0-2,MODERATE,MODERATE,UTI
209,15.0,MALE,FILIPINO,SINGLE,INCREASED,YELLOW,CLEAR,1.005,5.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,RARE,FEW,0-2,0-2,FEW,RARE,NEGATIVE
398,64.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.005,6.5,TRACE,NEGATIVE,NEGATIVE,3+,NEGATIVE,1,NEGATIVE,1+,MODERATE,MODERATE,10-20,5-10,MODERATE,MANY,UTI
27,20.0,FEMALE,FILIPINO,SINGLE,DECREASED,YELLOW,CLOUDY,1.010,6.0,1+,POSITIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,MANY,MANY,0-2,10-20,MANY,MANY,UTI
14,25.0,MALE,FILIPINO,SINGLE,DECREASED,YELLOW,HAZY,1.010,7.0,2+,NEGATIVE,NEGATIVE,NEGATIVE,TRACE,1,TRACE,NEGATIVE,FEW,MODERATE,0-2,20-30,MODERATE,MODERATE,UTI
144,22.0,MALE,FILIPINO,SINGLE,DECREASED,AMBER,TURBID,1.025,7.0,3+,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,3+,MANY,MANY,TNTC,TNTC,MODERATE,MANY,UTI
65,34.0,FEMALE,FILIPINO,MARRIED,DECREASED,LIGHT YELLOW,HAZY,1.010,6.0,2+,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,MODERATE,MODERATE,0-2,20-30,FEW,FEW,UTI
181,32.0,FEMALE,FILIPINO,SINGLE,DECREASED,LIGHT YELLOW,HAZY,1.010,6.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,RARE,MODERATE,0-2,0-2,FEW,RARE,NEGATIVE
145,36.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.010,6.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,RARE,FEW,0-2,0-2,FEW,FEW,NEGATIVE
217,7.0,MALE,FILIPINO,SINGLE,DECREASED,YELLOW,HAZY,1.020,6.0,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,1,NEGATIVE,NEGATIVE,RARE,MODERATE,0-2,0-2,MODERATE,RARE,NEGATIVE

In [12]:

binary_columns = {
    'DIAGNOSIS': {'UTI': 1, 'NEGATIVE': 0},
    'Clarity': {'INCREASED': 1, 'DECREASED': 0},
}

ordinal_mappings = {
    'Color': ['CLEAR', 'PALE YELLOW', 'STRAW', 'LIGHT YELLOW', 'YELLOW', 'DARK YELLOW', 'AMBER', 'BROWN', 'RED'],
    'Transparency': ['CLEAR',  'HAZY', 'CLOUDY', 'MILKY', 'TURBID'],
    # Chemical
    'Nitrite': ['NEGATIVE', 'TRACE', 'POSITIVE'],
    'Protein': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Leukocytes': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Glucose': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Ketones': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Bilirubin': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Blood': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    # Microscopic
    'Bacteria': ['RARE', 'FEW', 'MODERATE', 'MANY', 'TNTC'],
    'Epithelial Cells': ['RARE', 'FEW', 'MODERATE', 'MANY', 'TNTC'],
    'RBC': ['0-2', ' 5-10', ' 10-20', '20-30', 'TNTC'],
    'WBC': ['0-2', ' 5-10', ' 10-20', '20-30', 'TNTC'],
    'Mucus Threads': ['RARE', 'FEW', 'MODERATE', 'MANY', 'TNTC'],
    'Amorphous Urate/Phosphate': ['RARE', 'FEW', 'MODERATE', 'MANY', 'TNTC'],

}

for col, mapping in binary_columns.items():
    df[col] = df[col].map(mapping)



for col, order in ordinal_mappings.items():
    df[col] = pd.Categorical(df[col], categories=order, ordered=True).codes

one_hot_cols = ['Marital Status']

df = pd.get_dummies(df, columns=one_hot_cols)

df['FEMALE'] = df['Sex'].apply(lambda x: True if x == 'FEMALE' else False)
df = df.drop(columns=['Sex'])


df['FILIPINO'] = df['Ethnicity'].apply(lambda x: True if x == 'FILIPINO' else False)
df = df.drop(columns=['Ethnicity'])

In [13]:
df.head(30)

,Age,Clarity,Color,Transparency,Spec Gravity,pH Level,Leukocytes,Nitrite,Protein,Glucose,Ketones,Urobilinogen,Bilirubin,Blood,Bacteria,Epithelial Cells,RBC,WBC,Mucus Threads,Amorphous Urate/Phosphate,DIAGNOSIS,Marital Status_MARRIED,Marital Status_SINGLE,Marital Status_WIDOW,FEMALE,FILIPINO
0,23.0,1,4,0,1.005,5.0,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,False,True,False,True,True
1,44.0,0,4,2,1.020,6.0,0,0,0,0,0,1,0,3,1,3,3,0,3,0,0,True,False,False,True,True
2,22.0,0,5,1,1.025,6.0,0,0,2,3,1,1,0,0,2,2,0,0,1,1,0,False,True,False,True,True
3,16.0,0,5,1,1.020,5.0,0,0,0,0,0,1,0,0,1,1,0,0,2,0,0,False,True,False,True,True
4,18.0,0,3,1,1.005,6.5,0,0,0,0,0,1,0,0,1,2,0,0,1,0,0,False,True,False,False,True
5,38.0,0,3,1,1.010,7.0,0,0,0,0,0,1,0,4,2,2,4,4,2,2,1,True,False,False,True,True
6,32.0,0,4,1,1.020,5.0,0,0,0,0,0,1,0,0,1,2,0,0,1,0,0,True,False,False,False,True
7,38.0,0,4,4,1.015,5.0,4,0,0,0,0,1,0,3,3,3,3,4,3,3,1,True,False,False,True,True
8,37.0,0,4,4,1.030,5.0,1,0,1,0,0,1,0,3,3,3,3,1,2,2,1,True,False,False,True,True
9,11.0,0,4,1,1.010,6.5,1,1,0,0,0,1,0,0,2,3,0,1,1,1,1,False,True,False,True,True
10,52.0,0,4,1,1.005,6.5,0,0,0,0,0,1,0,0,0,1,0,0,2,0,0,True,False,False,True,True
11,22.0,0,4,2,1.025,6.5,0,0,0,0,0,1,0,0,1,2,0,0,2,0,0,False,True,False,True,True
12,51.0,0,4,1,1.020,6.0,0,0,0,0,0,1,0,0,1,2,0,0,1,0,0,True,False,False,True,True
13,35.0,0,4,1,1.030,7.0,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,True,False,False,True,True
14,25.0,0,4,1,1.010,7.0,3,0,0,0,1,1,1,0,1,2,0,3,2,2,1,False,True,False,False,True
15,17.0,0,5,4,1.015,6.5,1,1,1,0,0,1,0,3,4,4,3,1,3,3,1,False,True,False,True,True
16,53.0,0,4,2,1.010,7.0,2,0,1,0,0,1,0,4,2,2,3,1,3,1,1,True,False,False,True,True
17,59.0,0,4,1,1.005,6.5,0,0,0,0,0,1,0,4,1,2,3,0,1,1,0,True,False,False,False,True
18,12.0,0,5,1,1.020,5.0,1,0,0,0,0,1,0,3,2,2,3,1,1,1,1,False,True,False,False,True
19,60.0,0,4,1,1.020,5.0,1,1,0,0,0,1,0,0,2,2,0,0,1,1,1,True,False,False,True,True
20,25.0,0,4,1,1.025,5.0,0,0,1,0,0,1,0,2,1,1,2,0,1,0,0,False,True,False,False,True
21,36.0,1,4,0,1.010,6.0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,True,False,False,False,True
22,41.0,0,4,2,1.025,6.0,2,2,1,0,0,1,0,0,3,3,0,1,1,3,1,True,False,False,True,True
23,35.0,0,3,1,1.005,6.0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,False,True,False,True,True
24,28.0,0,6,2,1.025,5.0,0,0,2,0,0,1,0,0,3,3,0,0,3,1,1,False,True,False,False,True
25,37.0,0,4,1,1.025,5.0,0,0,1,0,1,1,0,0,1,1,0,0,3,0,0,True,False,False,False,True
26,26.0,0,5,1,1.030,5.0,0,0,1,1,0,1,0,0,1,1,0,0,1,0,0,False,True,False,False,True
27,20.0,0,4,2,1.010,6.0,2,2,0,0,0,1,0,0,3,3,0,2,3,3,1,False,True,False,True,True
28,23.0,0,4,1,1.020,5.0,1,0,0,0,0,1,0,0,2,1,0,1,1,1,0,False,True,False,False,True
29,12.0,0,4,4,1.015,5.0,0,2,1,2,0,1,0,0,3,3,0,0,3,3,1,False,True,False,False,True

In [14]:
negative_ones = (df == -1)

# Displaying rows with -1 values
rows_with_negative_ones = df[negative_ones.any(axis=1)]
print(rows_with_negative_ones)

Empty DataFrame
Columns: [Age, Clarity, Color, Transparency, Spec Gravity, pH Level, Leukocytes, Nitrite, Protein, Glucose, Ketones, Urobilinogen, Bilirubin, Blood, Bacteria, Epithelial Cells, RBC, WBC, Mucus Threads, Amorphous Urate/Phosphate, DIAGNOSIS, Marital Status_MARRIED, Marital Status_SINGLE, Marital Status_WIDOW, FEMALE, FILIPINO]
Index: []

In [15]:
df.sample(5)

,Age,Clarity,Color,Transparency,Spec Gravity,pH Level,Leukocytes,Nitrite,Protein,Glucose,Ketones,Urobilinogen,Bilirubin,Blood,Bacteria,Epithelial Cells,RBC,WBC,Mucus Threads,Amorphous Urate/Phosphate,DIAGNOSIS,Marital Status_MARRIED,Marital Status_SINGLE,Marital Status_WIDOW,FEMALE,FILIPINO
406,22.0,0,4,1,1.010,6.0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,False,True,False,True,True
169,1.0,0,4,1,1.030,6.0,0,0,0,0,0,1,0,0,0,2,0,0,1,0,0,False,True,False,False,True
111,33.0,0,3,1,1.005,5.0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,False,True,False,True,True
149,12.0,0,4,1,1.020,6.0,0,0,1,0,0,1,0,0,1,1,0,0,2,0,0,False,True,False,False,True
110,36.0,0,4,1,1.015,5.0,1,0,0,0,0,1,0,3,3,2,3,1,1,1,1,True,False,False,True,True

In [16]:
df.to_csv("encoded_dataset.csv")

In [17]:
null_rows = df[df.isnull().any(axis=1)]
print("Rows with null values:")
print(null_rows)

Rows with null values:
Empty DataFrame
Columns: [Age, Clarity, Color, Transparency, Spec Gravity, pH Level, Leukocytes, Nitrite, Protein, Glucose, Ketones, Urobilinogen, Bilirubin, Blood, Bacteria, Epithelial Cells, RBC, WBC, Mucus Threads, Amorphous Urate/Phosphate, DIAGNOSIS, Marital Status_MARRIED, Marital Status_SINGLE, Marital Status_WIDOW, FEMALE, FILIPINO]
Index: []