In [96]:
import pandas as pd

In [ ]:
df = pd.read_csv('final_dataset.csv')

In [ ]:
df = df.iloc[:, 1:]

In [101]:
for column in df.columns:
    print(f"Unique values in {column}:")
    print(df[column].unique())  
    print()

Unique values in Age:
[2.300e+01 4.400e+01 2.200e+01 1.600e+01 1.800e+01 3.800e+01 3.200e+01
 3.700e+01 1.100e+01 5.200e+01 5.100e+01 3.500e+01 2.500e+01 1.700e+01
 5.300e+01 5.900e+01 1.200e+01 6.000e+01 3.600e+01 4.100e+01 2.800e+01
 2.600e+01 2.000e+01 1.300e+01 4.000e+01 3.000e+01 4.000e+00 4.500e+01
 1.500e+01 6.667e-01 3.000e+00 6.000e+00 1.000e+01 1.000e+00 5.000e+01
 8.000e+00 3.300e+01 4.600e+01 5.700e+01 3.400e+01 2.700e+01 7.300e+01
 6.600e+01 3.100e+01 2.900e+01 4.300e+01 7.700e+01 4.700e+01 2.400e+01
 5.800e+01 1.400e+01 1.900e+01 5.600e+01 2.100e+01 4.900e+01 4.800e+01
 4.200e+01 5.000e+00 5.500e+01 3.900e+01 5.400e+01 2.000e+00 7.000e+00
 8.330e-02 6.300e+01 9.000e+00 8.800e+01 5.000e-01 6.200e+01 7.200e+01
 8.200e+01 6.400e+01 6.500e+01]

Unique values in Sex:
['FEMALE' 'MALE']

Unique values in Ethnicity:
['FILIPINO' 'INDIAN']

Unique values in Marital Status:
['SINGLE' 'MARRIED' 'WIDOW']

Unique values in Clarity:
['INCREASEDD' 'DECREASED' 'INCREASED']

Unique values in Color:
['YELLOW' 'DARK YELLOW' 'LIGHT YELLOW' 'AMBER' 'CLEAR' 'PALE YELLOW' 'RED'
 'BROWN' 'STRAW']

Unique values in Transparency:
['CLEAR' 'CLOUDY' 'HAZY' 'TURBID' 'MILKY' 'RED']

Unique values in Spec Gravity:
[1.005 1.02  1.025 1.01  1.015 1.03 ]

Unique values in pH Level:
[5.  6.  6.5 7.  7.5 8. ]

Unique values in Leukocytes:
['NEGATIVE' '3+' 'TRACE' '2+' '1+']

Unique values in Nitrite:
['NEGATIVE' 'TRACE' 'POSITIVE' '2+']

Unique values in Protein:
['NEGATIVE' '1+' 'TRACE' '2+' '3+' '4+']

Unique values in Glucose:
['NEGATIVE' '2+' 'TRACE' '1+' '3+' '4+']

Unique values in Ketones:
['NEGATIVE' 'TRACE' '3+' '1+' '4+' '2+']

Unique values in Urobilinogen:
['NORMAL' '4 mg/dL' '1 MG/DL']

Unique values in Bilirubin:
['NEGATIVE' 'TRACE' '2+' '3+' '1+']

Unique values in Blood:
['NEGATIVE' '2+' '3+' '1+' 'TRACE']

Unique values in Bacteria:
['FEW' 'MODERATE' 'MANY' 'RARE' 'TNTC']

Unique values in Epithelial Cells:
['FEW' 'MANY' 'MODERATE' 'TNTC' 'RARE' 'M0DE']

Unique values in RBC:
['0-2' '20-30' 'TNTC' '10-20' '5-10' 'RARE']

Unique values in WBC:
['0-2' 'TNTC' '5-10' '20-30' 'RARE' '10-20' 'FEW' '0--2']

Unique values in Mucus Threads:
['FEW' 'MANY' 'MODERATE' 'RARE']

Unique values in Amorphous Urate/Phosphate:
[nan 'RARE' 'FEW' 'MODERATE' 'MANY' 'RAE']

Unique values in DIAGNOSIS:
['NEGATIVE' 'UTI']

In [102]:
null_rows = df[df.isnull().any(axis=1)]
print("Rows with null values:")
print(null_rows)

Rows with null values:
    Age     Sex Ethnicity Marital Status     Clarity   Color Transparency  \
0  23.0  FEMALE  FILIPINO         SINGLE  INCREASEDD  YELLOW        CLEAR

   Spec Gravity  pH Level Leukocytes  ... Urobilinogen Bilirubin     Blood  \
0         1.005       5.0   NEGATIVE  ...       NORMAL  NEGATIVE  NEGATIVE

  Bacteria Epithelial Cells  RBC  WBC Mucus Threads Amorphous Urate/Phosphate  \
0      FEW              FEW  0-2  0-2           FEW                       NaN

  DIAGNOSIS
0  NEGATIVE

[1 rows x 24 columns]

In [103]:
for column in df.columns:
    print(f"Unique values in {column}:")
    print(df[column].unique())  
    print()

Unique values in Age:
[2.300e+01 4.400e+01 2.200e+01 1.600e+01 1.800e+01 3.800e+01 3.200e+01
 3.700e+01 1.100e+01 5.200e+01 5.100e+01 3.500e+01 2.500e+01 1.700e+01
 5.300e+01 5.900e+01 1.200e+01 6.000e+01 3.600e+01 4.100e+01 2.800e+01
 2.600e+01 2.000e+01 1.300e+01 4.000e+01 3.000e+01 4.000e+00 4.500e+01
 1.500e+01 6.667e-01 3.000e+00 6.000e+00 1.000e+01 1.000e+00 5.000e+01
 8.000e+00 3.300e+01 4.600e+01 5.700e+01 3.400e+01 2.700e+01 7.300e+01
 6.600e+01 3.100e+01 2.900e+01 4.300e+01 7.700e+01 4.700e+01 2.400e+01
 5.800e+01 1.400e+01 1.900e+01 5.600e+01 2.100e+01 4.900e+01 4.800e+01
 4.200e+01 5.000e+00 5.500e+01 3.900e+01 5.400e+01 2.000e+00 7.000e+00
 8.330e-02 6.300e+01 9.000e+00 8.800e+01 5.000e-01 6.200e+01 7.200e+01
 8.200e+01 6.400e+01 6.500e+01]

Unique values in Sex:
['FEMALE' 'MALE']

Unique values in Ethnicity:
['FILIPINO' 'INDIAN']

Unique values in Marital Status:
['SINGLE' 'MARRIED' 'WIDOW']

Unique values in Clarity:
['INCREASEDD' 'DECREASED' 'INCREASED']

Unique values in Color:
['YELLOW' 'DARK YELLOW' 'LIGHT YELLOW' 'AMBER' 'CLEAR' 'PALE YELLOW' 'RED'
 'BROWN' 'STRAW']

Unique values in Transparency:
['CLEAR' 'CLOUDY' 'HAZY' 'TURBID' 'MILKY' 'RED']

Unique values in Spec Gravity:
[1.005 1.02  1.025 1.01  1.015 1.03 ]

Unique values in pH Level:
[5.  6.  6.5 7.  7.5 8. ]

Unique values in Leukocytes:
['NEGATIVE' '3+' 'TRACE' '2+' '1+']

Unique values in Nitrite:
['NEGATIVE' 'TRACE' 'POSITIVE' '2+']

Unique values in Protein:
['NEGATIVE' '1+' 'TRACE' '2+' '3+' '4+']

Unique values in Glucose:
['NEGATIVE' '2+' 'TRACE' '1+' '3+' '4+']

Unique values in Ketones:
['NEGATIVE' 'TRACE' '3+' '1+' '4+' '2+']

Unique values in Urobilinogen:
['NORMAL' '4 mg/dL' '1 MG/DL']

Unique values in Bilirubin:
['NEGATIVE' 'TRACE' '2+' '3+' '1+']

Unique values in Blood:
['NEGATIVE' '2+' '3+' '1+' 'TRACE']

Unique values in Bacteria:
['FEW' 'MODERATE' 'MANY' 'RARE' 'TNTC']

Unique values in Epithelial Cells:
['FEW' 'MANY' 'MODERATE' 'TNTC' 'RARE' 'M0DE']

Unique values in RBC:
['0-2' '20-30' 'TNTC' '10-20' '5-10' 'RARE']

Unique values in WBC:
['0-2' 'TNTC' '5-10' '20-30' 'RARE' '10-20' 'FEW' '0--2']

Unique values in Mucus Threads:
['FEW' 'MANY' 'MODERATE' 'RARE']

Unique values in Amorphous Urate/Phosphate:
[nan 'RARE' 'FEW' 'MODERATE' 'MANY' 'RAE']

Unique values in DIAGNOSIS:
['NEGATIVE' 'UTI']

In [104]:
df.head(20)

,Age,Sex,Ethnicity,Marital Status,Clarity,Color,Transparency,Spec Gravity,pH Level,Leukocytes,...,Urobilinogen,Bilirubin,Blood,Bacteria,Epithelial Cells,RBC,WBC,Mucus Threads,Amorphous Urate/Phosphate,DIAGNOSIS
0,23.0,FEMALE,FILIPINO,SINGLE,INCREASEDD,YELLOW,CLEAR,1.005,5.0,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,FEW,FEW,0-2,0-2,FEW,NaN,NEGATIVE
1,44.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,CLOUDY,1.020,6.0,NEGATIVE,...,NORMAL,NEGATIVE,2+,FEW,MANY,20-30,0-2,MANY,RARE,NEGATIVE
2,22.0,FEMALE,FILIPINO,SINGLE,DECREASED,DARK YELLOW,HAZY,1.025,6.0,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,MODERATE,MODERATE,0-2,0-2,FEW,FEW,NEGATIVE
3,16.0,FEMALE,FILIPINO,SINGLE,DECREASED,DARK YELLOW,HAZY,1.020,5.0,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,FEW,FEW,0-2,0-2,MODERATE,RARE,NEGATIVE
4,18.0,MALE,FILIPINO,SINGLE,DECREASED,LIGHT YELLOW,HAZY,1.005,6.5,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,FEW,MODERATE,0-2,0-2,FEW,RARE,NEGATIVE
5,38.0,FEMALE,FILIPINO,MARRIED,DECREASED,LIGHT YELLOW,HAZY,1.010,7.0,NEGATIVE,...,NORMAL,NEGATIVE,3+,MODERATE,MODERATE,TNTC,TNTC,MODERATE,MODERATE,UTI
6,32.0,MALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.020,5.0,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,FEW,MODERATE,0-2,0-2,FEW,RARE,NEGATIVE
7,38.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,TURBID,1.015,5.0,3+,...,NORMAL,NEGATIVE,2+,MANY,MANY,20-30,TNTC,MANY,MANY,UTI
8,37.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,TURBID,1.030,5.0,TRACE,...,NORMAL,NEGATIVE,2+,MANY,MANY,20-30,5-10,MODERATE,MODERATE,UTI
9,11.0,FEMALE,FILIPINO,SINGLE,DECREASED,YELLOW,HAZY,1.010,6.5,TRACE,...,NORMAL,NEGATIVE,NEGATIVE,MODERATE,MANY,0-2,5-10,FEW,FEW,UTI
10,52.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.005,6.5,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,RARE,FEW,0-2,0-2,MODERATE,RARE,NEGATIVE
11,22.0,FEMALE,FILIPINO,SINGLE,DECREASED,YELLOW,CLOUDY,1.025,6.5,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,FEW,MODERATE,0-2,0-2,MODERATE,RARE,NEGATIVE
12,51.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.020,6.0,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,FEW,MODERATE,0-2,0-2,FEW,RARE,NEGATIVE
13,35.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.030,7.0,NEGATIVE,...,NORMAL,NEGATIVE,NEGATIVE,FEW,FEW,0-2,0-2,FEW,RARE,NEGATIVE
14,25.0,MALE,FILIPINO,SINGLE,DECREASED,YELLOW,HAZY,1.010,7.0,2+,...,NORMAL,TRACE,NEGATIVE,FEW,MODERATE,0-2,20-30,MODERATE,MODERATE,UTI
15,17.0,FEMALE,FILIPINO,SINGLE,DECREASED,DARK YELLOW,TURBID,1.015,6.5,TRACE,...,NORMAL,NEGATIVE,2+,TNTC,TNTC,20-30,5-10,MANY,MANY,UTI
16,53.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,CLOUDY,1.010,7.0,1+,...,NORMAL,NEGATIVE,3+,MODERATE,MODERATE,20-30,5-10,MANY,FEW,UTI
17,59.0,MALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.005,6.5,NEGATIVE,...,NORMAL,NEGATIVE,3+,FEW,MODERATE,20-30,0-2,FEW,FEW,NEGATIVE
18,12.0,MALE,FILIPINO,SINGLE,DECREASED,DARK YELLOW,HAZY,1.020,5.0,TRACE,...,NORMAL,NEGATIVE,2+,MODERATE,MODERATE,20-30,5-10,FEW,FEW,UTI
19,60.0,FEMALE,FILIPINO,MARRIED,DECREASED,YELLOW,HAZY,1.020,5.0,TRACE,...,NORMAL,NEGATIVE,NEGATIVE,MODERATE,MODERATE,0-2,0-2,FEW,FEW,UTI

In [105]:
# df1.head(20)

In [106]:
# df1.columns

In [ ]:
binary_columns = {
    'DIAGNOSIS': {'UTI': 1, 'NEGATIVE': 0},
    'Clarity': {'INCREASED': 1, 'DECREASED': 0},
    'Urobilinogen': {'NORMAL' : 0, 'ABNORMAL': 1}
}

ordinal_mappings = {
    'Color': ['CLEAR', 'PALE YELLOW', 'STRAW' 'LIGHT YELLOW', 'YELLOW', 'DARK YELLOW', 'AMBER', 'BROWN', 'RED'],
    'Transparency': ['CLEAR',  'HAZY', 'CLOUDY', 'MILKY', 'TURBID', 'RED'],
    # Chemical
    'Nitrite': ['NEGATIVE', 'TRACE', 'POSITIVE'],
    'Protein': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Leukocytes': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Glucose': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Ketones': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Bilirubin': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    'Blood': ['NEGATIVE', 'TRACE', '1+', '2+', '3+', '4+'],
    # Microscopic
    'Bacteria': ['RARE', 'FEW', 'MODERATE', 'MANY', 'TNTC'],
    'Epithelial Cells': ['RARE', 'FEW', 'MODERATE', 'MANY', 'TNTC'],
    'RBC': ['0-2', '5-10', '10-20', '20-30', 'TNTC'],
    'WBC': ['0-2', '5-10', '10-20', '20-30', 'TNTC'],
    'Mucus Threads': ['RARE', 'FEW', 'MODERATE', 'MANY', 'TNTC'],
    'Amorphous Urate/Phosphate': ['RARE', 'FEW', 'MODERATE', 'MANY', 'TNTC'],

}

for col, mapping in binary_columns.items():
    df[col] = df[col].map(mapping)
    # df1[col] = df1[col].map(mapping)


for col, order in ordinal_mappings.items():
    df[col] = pd.Categorical(df[col], categories=order, ordered=True).codes

one_hot_cols = ['Marital Status']

df = pd.get_dummies(df, columns=one_hot_cols)

df['FEMALE'] = df['Sex'].apply(lambda x: True if x == 'FEMALE' else False)
df = df.drop(columns=['Sex'])


df['FILIPINO'] = df['Ethnicity'].apply(lambda x: True if x == 'FILIPINO' else False)
df = df.drop(columns=['Ethnicity'])

In [108]:
df.head(30)

,Age,Clarity,Color,Transparency,Spec Gravity,pH Level,Leukocytes,Nitrite,Protein,Glucose,...,RBC,WBC,Mucus Threads,Amorphous Urate/Phosphate,DIAGNOSIS,Marital Status_MARRIED,Marital Status_SINGLE,Marital Status_WIDOW,FEMALE,FILIPINO
0,23.0,NaN,3,0,1.005,5.0,0,0,0,0,...,0,0,1,-1,0,False,True,False,True,True
1,44.0,0.0,3,2,1.020,6.0,0,0,0,0,...,3,0,3,0,0,True,False,False,True,True
2,22.0,0.0,4,1,1.025,6.0,0,0,2,3,...,0,0,1,1,0,False,True,False,True,True
3,16.0,0.0,4,1,1.020,5.0,0,0,0,0,...,0,0,2,0,0,False,True,False,True,True
4,18.0,0.0,-1,1,1.005,6.5,0,0,0,0,...,0,0,1,0,0,False,True,False,False,True
5,38.0,0.0,-1,1,1.010,7.0,0,0,0,0,...,4,4,2,2,1,True,False,False,True,True
6,32.0,0.0,3,1,1.020,5.0,0,0,0,0,...,0,0,1,0,0,True,False,False,False,True
7,38.0,0.0,3,4,1.015,5.0,4,0,0,0,...,3,4,3,3,1,True,False,False,True,True
8,37.0,0.0,3,4,1.030,5.0,1,0,1,0,...,3,1,2,2,1,True,False,False,True,True
9,11.0,0.0,3,1,1.010,6.5,1,1,0,0,...,0,1,1,1,1,False,True,False,True,True
10,52.0,0.0,3,1,1.005,6.5,0,0,0,0,...,0,0,2,0,0,True,False,False,True,True
11,22.0,0.0,3,2,1.025,6.5,0,0,0,0,...,0,0,2,0,0,False,True,False,True,True
12,51.0,0.0,3,1,1.020,6.0,0,0,0,0,...,0,0,1,0,0,True,False,False,True,True
13,35.0,0.0,3,1,1.030,7.0,0,0,0,0,...,0,0,1,0,0,True,False,False,True,True
14,25.0,0.0,3,1,1.010,7.0,3,0,0,0,...,0,3,2,2,1,False,True,False,False,True
15,17.0,0.0,4,4,1.015,6.5,1,1,1,0,...,3,1,3,3,1,False,True,False,True,True
16,53.0,0.0,3,2,1.010,7.0,2,0,1,0,...,3,1,3,1,1,True,False,False,True,True
17,59.0,0.0,3,1,1.005,6.5,0,0,0,0,...,3,0,1,1,0,True,False,False,False,True
18,12.0,0.0,4,1,1.020,5.0,1,0,0,0,...,3,1,1,1,1,False,True,False,False,True
19,60.0,0.0,3,1,1.020,5.0,1,1,0,0,...,0,0,1,1,1,True,False,False,True,True
20,25.0,0.0,3,1,1.025,5.0,0,0,1,0,...,2,-1,1,0,0,False,True,False,False,True
21,36.0,1.0,3,0,1.010,6.0,0,0,0,0,...,0,0,1,0,0,True,False,False,False,True
22,41.0,0.0,3,2,1.025,6.0,2,2,1,0,...,0,1,1,3,1,True,False,False,True,True
23,35.0,0.0,-1,1,1.005,6.0,0,0,0,0,...,0,0,1,0,0,False,True,False,True,True
24,28.0,0.0,5,2,1.025,5.0,0,0,2,0,...,0,0,3,1,1,False,True,False,False,True
25,37.0,0.0,3,1,1.025,5.0,0,0,1,0,...,0,0,3,0,0,True,False,False,False,True
26,26.0,0.0,4,1,1.030,5.0,0,0,1,1,...,0,0,1,0,0,False,True,False,False,True
27,20.0,0.0,3,2,1.010,6.0,2,2,0,0,...,0,2,3,3,1,False,True,False,True,True
28,23.0,0.0,3,1,1.020,5.0,1,0,0,0,...,0,1,1,1,0,False,True,False,False,True
29,12.0,0.0,3,4,1.015,5.0,0,2,1,2,...,0,0,3,3,1,False,True,False,False,True

In [109]:
negative_ones = (df == -1)

# Displaying rows with -1 values
rows_with_negative_ones = df[negative_ones.any(axis=1)]
print(rows_with_negative_ones)

         Age  Clarity  Color  Transparency  Spec Gravity  pH Level  \
0    23.0000      NaN      3             0         1.005       5.0
4    18.0000      0.0     -1             1         1.005       6.5
5    38.0000      0.0     -1             1         1.010       7.0
20   25.0000      0.0      3             1         1.025       5.0
23   35.0000      0.0     -1             1         1.005       6.0
31   40.0000      0.0     -1             1         1.015       6.0
33   59.0000      0.0     -1             1         1.005       6.0
54    1.0000      0.0     -1             1         1.005       7.5
55   32.0000      0.0     -1             1         1.005       6.0
56   23.0000      0.0     -1             1         1.005       5.0
62   33.0000      0.0     -1             1         1.005       6.5
63   46.0000      0.0     -1             1         1.015       6.0
65   34.0000      0.0     -1             1         1.010       6.0
70   38.0000      0.0     -1             1         1.010       6.0
80   35.0000      0.0     -1             4         1.010       6.5
82   30.0000      0.0     -1             1         1.005       6.0
84   60.0000      0.0     -1             4         1.025       7.0
85   29.0000      0.0     -1             1         1.010       6.5
97   60.0000      0.0     -1             1         1.005       5.0
102  30.0000      0.0      6             4         1.025       6.5
104  29.0000      0.0     -1             1         1.030       6.0
111  33.0000      0.0     -1             1         1.005       5.0
115  27.0000      0.0     -1             1         1.010       5.0
116  33.0000      0.0     -1             1         1.005       5.0
122  22.0000      0.0     -1             1         1.015       5.0
123  49.0000      0.0     -1             1         1.015       5.0
127  48.0000      0.0     -1             1         1.010       5.0
140  44.0000      0.0     -1             4         1.010       8.0
150  28.0000      1.0     -1             0         1.005       5.0
151  32.0000      0.0     -1             1         1.010       6.5
153   0.6667      0.0     -1             1         1.005       6.0
169   1.0000      0.0      3             1         1.030       6.0
181  32.0000      0.0     -1             1         1.010       6.0
205  18.0000      1.0     -1             0         1.005       6.0
211  55.0000      0.0      4             1         1.015       6.0
261  14.0000      0.0     -1             1         1.010       5.0
288  20.0000      1.0     -1             0         1.005       6.5
294  31.0000      0.0      3             1         1.005       6.0
353  19.0000      0.0      1             1         1.015       6.0
363   0.5000      0.0     -1             1         1.005       6.0
365  42.0000      1.0     -1             0         1.005       5.0
377   6.0000      0.0     -1             1         1.005       5.0
378  48.0000      0.0     -1             1         1.010       5.0
382   5.0000      0.0     -1             1         1.005       6.5
385  33.0000      0.0     -1             1         1.010       6.5
387  66.0000      0.0     -1             1         1.005       6.5
392  56.0000      1.0     -1             0         1.005       5.0
399  58.0000      0.0     -1             1         1.005       6.0
400   8.0000      0.0     -1             1         1.005       6.5
407  24.0000      0.0     -1             1         1.010       6.0
408  46.0000      0.0     -1             1         1.015       6.0
409  33.0000      0.0     -1             1         1.025       6.0

     Leukocytes  Nitrite  Protein  Glucose  ...  RBC  WBC  Mucus Threads  \
0             0        0        0        0  ...    0    0              1
4             0        0        0        0  ...    0    0              1
5             0        0        0        0  ...    4    4              2
20            0        0        1        0  ...    2   -1              1
23            0        0        0        0  ...    0    0              1
31            2        0        0        0  ...    0    2              1
33            2        0        0        0  ...    0    2              3
54            1        0        0        0  ...    0    1              1
55            0        0        0        0  ...    0    0              2
56            2        0        1        0  ...    0    1              1
62            0        0        0        0  ...    0    0              1
63            0        0        0        0  ...    0    0              2
65            3        0        0        0  ...    0    3              1
70            0        0        0        0  ...    0    0              1
80            3        0        1        0  ...    0    3              3
82            0        0        0        0  ...    0    0              1
84            4        0        1        0  ...    4    4              3
85            1        0        0        0  ...    2    1              1
97            0        0        0        0  ...    0    0              2
102           4       -1        1        0  ...    4    4              3
104           0        0        1        0  ...    0    0              1
111           0        0        0        0  ...    0    0              1
115           1        0        0        0  ...    0    1              1
116           0        0        0        0  ...    0    0              1
122           4        0        0        0  ...    0    4              2
123           0        0        0        4  ...    0    0              2
127           1        0        0        0  ...    4    1              2
140           3        0        0        0  ...    3    3              2
150           0        0        0        0  ...    0    0              2
151           0        0        0        0  ...    0    0              2
153           0        0        0        0  ...    0    0              1
169           0        0        0        0  ...    0    0              1
181           0        0        0        0  ...    0    0              1
205           0        0        0        0  ...    0    0              1
211           2        0        0        0  ...    0    2              2
261           0        0        0        0  ...    0    0              1
288           0        0        0        0  ...    0    0              0
294           0        0        0        1  ...   -1   -1              1
353           0        0        0        0  ...    0   -1              1
363           0        0        0        0  ...    0    0              1
365           0        0        0        0  ...    0    0              1
377           1        0        0        0  ...    1    1              2
378           1        0        0        0  ...    0    1              1
382           1        0        0        0  ...    1    1              2
385           0        0        0        0  ...    0    0              1
387           1        0        0        0  ...    0    1              2
392           0        0        0        0  ...    0    0              1
399           2        0        0        0  ...    0    1              1
400           1        0        0        0  ...    0    1              2
407           0        0        0        0  ...    0    0              1
408           0        0        0        0  ...    0    0              1
409           0        0        0        0  ...    0    0              2

     Amorphous Urate/Phosphate  DIAGNOSIS  Marital Status_MARRIED  \
0                           -1          0                   False
4                            0          0                   False
5                            2          1                    True
20                           0          0                   False
23                           0          0                   False
31                           1          1                    True
33                           1          1                    True
54                           0          1                   False
55                           0          0                    True
56                           1          1                   False
62                           0          0                   False
63                           0          0                    True
65                           1          1                    True
70                           0          0                    True
80                           3          1                    True
82                           1          0                   False
84                           3          1                   False
85                           0          0                   False
97                           1          0                    True
102                          3          1                   False
104                          1          0                   False
111                          0          0                   False
115                          1          1                   False
116                          0          0                    True
122                          2          1                   False
123                          0          0                    True
127                          0          0                    True
140                          2          1                    True
150                          0          0                   False
151                          0          0                    True
153                          1          0                   False
169                         -1          0                   False
181                          0          0                   False
205                          0          0                   False
211                          2          1                    True
261                          0          0                   False
288                          0          0                   False
294                          1          0                    True
353                          0          0                   False
363                          0          0                   False
365                          0          0                    True
377                          1          1                   False
378                          1          1                    True
382                          2          1                   False
385                          0          0                   False
387                          2          1                    True
392                          0          0                    True
399                          1          1                    True
400                          1          1                   False
407                          0          0                   False
408                          0          0                    True
409                          0          0                    True

     Marital Status_SINGLE  Marital Status_WIDOW  FEMALE  FILIPINO
0                     True                 False    True      True
4                     True                 False   False      True
5                    False                 False    True      True
20                    True                 False   False      True
23                    True                 False    True      True
31                   False                 False   False      True
33                   False                 False    True      True
54                    True                 False   False      True
55                   False                 False    True      True
56                    True                 False    True      True
62                    True                 False    True      True
63                   False                 False   False      True
65                   False                 False    True      True
70                   False                 False   False      True
80                   False                 False    True      True
82                    True                 False   False      True
84                    True                 False    True      True
85                    True                 False    True      True
97                   False                 False   False      True
102                   True                 False   False      True
104                   True                 False   False      True
111                   True                 False    True      True
115                   True                 False    True      True
116                  False                 False    True      True
122                   True                 False    True      True
123                  False                 False   False      True
127                  False                 False    True     False
140                  False                 False    True      True
150                   True                 False    True      True
151                  False                 False    True      True
153                   True                 False   False      True
169                   True                 False   False      True
181                   True                 False    True      True
205                   True                 False   False      True
211                  False                 False    True      True
261                   True                 False    True      True
288                   True                 False    True      True
294                  False                 False    True      True
353                   True                 False    True      True
363                   True                 False   False      True
365                  False                 False   False      True
377                   True                 False    True      True
378                  False                 False   False      True
382                   True                 False    True      True
385                   True                 False    True      True
387                  False                 False    True      True
392                  False                 False    True      True
399                  False                 False    True      True
400                   True                 False   False      True
407                   True                 False    True      True
408                  False                 False    True      True
409                  False                 False    True      True

[52 rows x 26 columns]